export const COPY = {
  tituloApp: "Pomodoro",
  foco: "Foco",
  pausa: "Pausa",
  pausaLonga: "Pausa longa",
  iniciar: "Iniciar",
  iniciarFoco: "Iniciar foco",
  iniciarPausa: "Iniciar pausa",
  iniciarPausaLonga: "Iniciar pausa longa",
  pausar: "Pausar",
  retomar: "Retomar",
  pular: "Pular",
  resetar: "Resetar",
  configuracoes: "Configurações",
  voltar: "Voltar",
  salvar: "Salvar",
  overlayPararTitulo: "Hora de parar",
  overlayPararTexto: "A sessão de foco acabou. Faça uma pausa.",
  overlayVoltarTitulo: "Hora de voltar ao foco",
  overlayVoltarTexto: "A pausa acabou.",
  overlayPausaLongaTexto: "A pausa longa acabou.",
  dispensar: "Entendi",
  tituloTimer: "Timer",
  slogan: "Foque • Pause • Continue",
  cicloCartao: "Ciclo",
  pularAjuda: "Avançar modo",
  recadoFoco: "Hora de focar",
  recadoFocoAndamento: "Foque agora",
  recadoFocoPausado: "Foco pausado",
  recadoPausa: "Hora da pausa",
  recadoPausaAndamento: "Pausa em andamento",
  recadoPausaPausada: "Pausa pausada",
  recadoPausaLonga: "Hora da pausa longa",
  recadoPausaLongaAndamento: "Pausa longa em andamento",
  editarChip: "Editar",
  editarTempos: "Tempos",
  configTitulo: "Ciclos",
  configAjuda:
    "O ciclo é foco e pausa 3 vezes; depois um 4º foco e uma pausa longa.",
  configFoco: "Foco (minutos)",
  configPausa: "Pausa (minutos)",
  configPausaLonga: "Pausa longa (minutos)",
  configErro: "Use minutos inteiros entre 1 e 180.",
  iconeFlutuante: "Pomodoro",
} as const;
