export const COPY = {
  tituloApp: "Pomodoro",
  foco: "Foco",
  pausa: "Pausa",
  pausaLonga: "Pausa longa",
  iniciar: "Iniciar",
  iniciarFoco: "Iniciar foco",
  iniciarPausa: "Iniciar pausa",
  iniciarPausaLonga: "Iniciar pausa longa",
  pausar: "Pausar",
  retomar: "Retomar",
  pular: "Pular",
  resetar: "Resetar",
  configuracoes: "Configurações",
  voltar: "Voltar",
  salvar: "Salvar",
  overlayPararTitulo: "Hora de parar",
  overlayPararTexto: "A sessão de foco acabou. Faça uma pausa.",
  overlayVoltarTitulo: "Hora de voltar ao foco",
  overlayVoltarTexto: "A pausa acabou.",
  overlayPausaLongaTexto: "A pausa longa acabou.",
  dispensar: "Entendi",
  cancelar: "Cancelar",
  editarRecado: "Editar próxima mensagem",
  recadoOverlayTitulo: "Próxima mensagem",
  recadoOverlayAjuda:
    "Vale só para o próximo aviso ao zerar. Depois volta o texto padrão.",
  recadoOverlayCampo: "Texto do aviso",
  tituloTimer: "Timer",
  slogan: "Foque • Pause • Continue",
  cicloCartao: "Ciclo",
  pularAjuda: "Avançar modo",
  recadoFoco: "Hora de focar",
  recadoFocoAndamento: "Foque agora",
  recadoFocoPausado: "Foco pausado",
  recadoPausa: "Hora da pausa",
  recadoPausaAndamento: "Pausa em andamento",
  recadoPausaPausada: "Pausa pausada",
  recadoPausaLonga: "Hora da pausa longa",
  recadoPausaLongaAndamento: "Pausa longa em andamento",
  editarChip: "Editar",
  editarTempos: "Tempos",
  configTitulo: "Ciclos",
  configFoco: "Foco (minutos)",
  configPausa: "Pausa (minutos)",
  configPausaLonga: "Pausa longa (minutos)",
  configErro: "Use minutos inteiros entre 1 e 180.",
  configTempo: "Tempo",
  configSom: "Som",
  configSonsClassicos: "Clássicos",
  configSonsGerais: "Notificações",
  configSomNenhum: "Nenhum",
  configSomFoco: "Som ao fim do foco",
  configSomPausa: "Som ao fim da pausa curta",
  configSomPausaLonga: "Som ao fim da pausa longa",
  configAltura: "Altura",
  configLoop: "Tocar em looping",
  configOuvir: "Ouvir",
  iconeFlutuante: "Pomodoro",
  atualizacaoTitulo: "Há uma atualização",
  atualizacaoTexto: "Uma versão nova do Pomodoro está disponível.",
  atualizacaoAtualizar: "Atualizar",
  atualizacaoAgoraNao: "Agora não",
  atualizacaoBaixando: "Baixando atualização…",
  atualizacaoErro:
    "Não foi possível baixar a atualização. Tente de novo quando a internet estiver ok.",
} as const;
